admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_quiz_new:
    path:   /new
    defaults: { _controller: AdminBundle:Quiz:new }

admin_quiz_list:
    path:   /list
    defaults: { _controller: AdminBundle:Quiz:list }

admin_quiz_edit:
    path:   /edit/{id}
    defaults: { _controller: AdminBundle:Quiz:edit }

admin_quiz_delete:
    path:   /delete/{id}
    defaults: { _controller: AdminBundle:Quiz:delete }

