admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

voter:
    resource: "@VoterBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"